[character]
error_symbol = "[](bold red) "

[cmd_duration]
format = "  took ${duration}"

[git_branch]
disabled = true

[git_status]
disabled = true

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[directory]
truncate_to_repo = false
truncation_length = 5
read_only = " "

[gcloud]
disabled = true

[aws]
symbol = "󰅟  "

[bun]
symbol = " "
style = "#f9f1e1"

[c]
symbol = " "

[docker_context]
symbol = "  "

[elixir]
symbol = " "

[gleam]
symbol = "󰦥 "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[deno]
symbol = " "
style = "#b5a2d1"

[swift]
symbol = " "

[ocaml]
symbol = " "
style = "#ed6b0d"

[package]
symbol = " "

[python]
symbol = " "
style = "#3f7dae"

[rust]
symbol = " "
style = "#ff812d"

[zig]
symbol = " "
style = "#f7a41c"
