[character]
error_symbol = "[ï€](bold red) "

[cmd_duration]
format = " ï‰“ took ${duration}"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "âœ˜${count}"

[directory]
truncate_to_repo = false
truncation_length = 5
read_only = " ï ½"

[gcloud]
disabled = true

[aws]
symbol = "ó°…Ÿ  "

[bun]
symbol = "î¯ "
style = "#f9f1e1"

[c]
symbol = "î˜ "

[docker_context]
symbol = "ïˆŸ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "ğŸŒ³ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "ó°Ÿ“ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "îœ¸ "

[memory_usage]
symbol = "ï¡š "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î´ "

[deno]
symbol = "îŸ€ "
style = "#b5a2d1"

[swift]
symbol = "îš™ "

[ocaml]
symbol = "ğŸ« "
style = "#f28c04"

[package]
symbol = "ï’‡ "

[python]
symbol = "î˜† "
style = "#3f7dae"

[rust]
symbol = "î¨ "
style = "#ff812d"

[zig]
symbol = "î£¯ "
style = "#f7a41c"
