[character]
error_symbol = "[ï€](bold red) "

[cmd_duration]
format = " ï‰“ took ${duration}"

[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "âœ˜${count}"

[directory]
truncate_to_repo = false
truncation_length = 5
read_only = " ï ½"

[gcloud]
disabled = true

[bun]
symbol = "ğŸ¥Ÿ "

[c]
symbol = "î˜ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ğŸ³ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "ğŸŒ³ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "ğŸ¹ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "â˜• "

[memory_usage]
symbol = "ï¡š "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[ocaml]
symbol = "ğŸ« "

[package]
symbol = "ğŸ“¦ "

[python]
symbol = "ğŸ "

[rust]
symbol = "ğŸ¦€ "

[zig]
symbol = "ğŸ¦ "

